# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install git-lfs libsndfile1-dev cmake g++
        python -m pip install --upgrade pip
        python -m pip install flake8
        python -m pip install -e .[dev]
    - name: Check out git-lfs
      run: |
        git lfs pull
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with black
      run: |
        black --check .
    - name: Check types with mypy
      run: |
        mypy python/oddvoices tests
    - name: Build C++ tool
      run: |
        cd liboddvoices
        mkdir build
        cd build
        cmake ..
        make
    - name: Test with pytest
      run: |
        pytest
